services:
  jekyll:
    image: ruby:3.2
    command: >
      bash -c "bundle install &&
      bundle exec jekyll serve --host 0.0.0.0 --force_polling --livereload"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
